### ISSUE TITLE
Что то не хочет грузить зависимости

### ISSUE THREAD

**Issue by Radzhab** [KKorvin/TinyStockQuotes#1]
Доброе время суток. Запускаю ваш проект. Выдает 
![2015-04-30_16-32-10](https://cloud.githubusercontent.com/assets/2556411/7413710/aeee9dca-ef56-11e4-98c1-179b68ee629e.jpg)

**Comment by KKorvin** [comment]
Здравствуйте, проверте есть ли в файле TinyStockQuotes/build.gradle репозитории:
   jcenter()
   maven { url "https://jitpack.io" }

Есть ли у вас какие-нибудь ещё проекты с внешними зависимостями, которые можно запустить, чтобы убедить, что проблема с TinyStockQuotes, а не глобальная?

**Comment by Radzhab** [comment]
Да запускал сегодня много проектов. Все работало. Проблема возникла только с вашим проектом. Сейчас попробую с домашнего ПК запустить, позже отпишусь

**Comment by Radzhab** [comment]
Все работает) проблема в связи.

**Comment by KKorvin** [comment]
Отлично)
